SET NAMES 'utf8' COLLATE 'utf8_general_ci' ;

set FOREIGN_KEY_CHECKS=0 ;

DELETE  FROM  `language` ;
INSERT INTO `language` (`id`, `label`) VALUES
	(1, 'afrikaans'),
	(2, 'albanais'),
	(3, 'allemand'),
	(4, 'anglais'),
	(5, 'arabe'),
	(6, 'arménien'),
	(7, 'azéri'),
	(8, 'bengali'),
	(9, 'breton'),
	(10, 'bulgare'),
	(11, 'catalan'),
	(12, 'chinois'),
	(13, 'coréen'),
	(14, 'croate'),
	(15, 'danois'),
	(16, 'espagnol'),
	(17, 'espéranto'),
	(18, 'estonien'),
	(19, 'fidjien'),
	(20, 'finnois'),
	(21, 'français'),
	(22, 'frison occidental'),
	(23, 'galicien'),
	(24, 'géorgien'),
	(25, 'grec'),
	(26, 'hébreu'),
	(27, 'hindi'),
	(28, 'hongrois'),
	(29, 'indonésien'),
	(30, 'irlandais'),
	(31, 'italien'),
	(32, 'japonais'),
	(33, 'kazakh'),
	(34, 'kurde'),
	(35, 'latin'),
	(36, 'letton'),
	(37, 'lingala'),
	(38, 'lituanien'),
	(39, 'macédonien'),
	(40, 'malais'),
	(41, 'malayalam'),
	(42, 'malgache'),
	(43, 'marathe'),
	(44, 'moldave'),
	(45, 'mongol'),
	(46, 'néerlandais'),
	(47, 'népalais'),
	(48, 'norvégien'),
	(49, 'ourdou'),
	(50, 'ouszbek'),
	(51, 'pachto'),
	(52, 'persan'),
	(53, 'polonais'),
	(54, 'portugais'),
	(55, 'romanche'),
	(56, 'roumain'),
	(57, 'russe'),
	(58, 'serbe'),
	(59, 'slovaque'),
	(60, 'slovène'),
	(61, 'somali'),
	(62, 'sotho du Sud'),
	(63, 'suédois'),
	(64, 'swahili'),
	(65, 'tagalog'),
	(66, 'tamoul'),
	(67, 'tchèque'),
	(68, 'thaï'),
	(69, 'turc'),
	(70, 'turkmène'),
	(71, 'ukrainien'),
	(72, 'vietnamien'),
	(73, 'yiddish');

	set FOREIGN_KEY_CHECKS=1