spring:
    application:
        name: happy-hoursService_prod
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:3306/happyhours?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: root
        hikari:
            data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
    jpa:
        database: MYSQL
        show_sql: true
        hibernate:
          ddl-auto : update
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    jmx:
        default-domain: ${spring.application.name}
    messages:
      basename: i18n/messages
      cache-seconds: 1
      always-use-message-format: true

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/uaa/user/current
    client:
      clientId: happy-hours-service
      clientSecret: happy-hours-service-secret
      accessTokenUri: http://localhost:7777/uaa/oauth/token
      userAuthorizationUri: http://localhost:7777/uaa/oauth/authorize
      grant-type: client_credentials
      scope: server

server:
    port: 8181

hystrix:
    threadpool.default:
        coreSize: 20
        maxQueueSize: 500000
        keepAliveTimeMinutes: 2
        queueSizeRejectionThreshold: 500000
    command.default:
        fallback.isolation.semaphore.maxConcurrentRequests: 20
        execution:
          timeout.enabled: false
          isolation:
            strategy: THREAD
            thread.timeoutInMilliseconds: 60000

flyway :
  enabled : false

# ===================================================================
# happy-hours specific properties
# ===================================================================

happy-hours:
    cache:
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    swagger:
        title: Happy-hours service  API
        description: Happy-hours API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license: Apache 2.0
        licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
    feign:
      communication: http://localhost:6060/ws
      auth : http://localhost:7777/uaa/
      medicalpartner: http://localhost:7080/ws
    photo:
      path: /home/ubuntu/workspace/storage
      url: http://83.166.136.134/storage

    security:
       authentication:
          oauth:
            clientid: acme
            secret: acmesecret
            scope:  read write
            grant_type : password
            grant_type_refresh : refresh_token
    test:
      token:
      enabled: false
      swagger:
              token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODQ4MTUzNzcsInVzZXJfbmFtZSI6ImFkbWluQGFnZW5kYS5jaCIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiODNlOTkzNTMtZjk0ZC00OTA3LThhZWEtZTE3ZGY0YWVlODdkIiwiY2xpZW50X2lkIjoiYWNtZSIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.B02ILySrPP8ftSCscgl-RrH5KTi7XynuOvIRZBUIUHuPI_uWvAJhTNVYFtfYUO2Am2dYqOpAjTNm53NGajLhWFlvfFsNyspC57WML0v2802lQwOKzoN-ayPbYGtRQgp3I1_FzAf5xUw2CwxewU5UeZrL5olro4zZvVTLgRG16ral2XaXt2g2P2I99ukMHVs7_g0s3Jw_rOBg21uub-ovIe9xQlB0kjAQI-K4xBGT46QhLwj5QP4Bgp2S8rzyAY6YiZQ7jIB622bX36vZH4cka7G8EWMS4dQOa2gSDc7e18Xnw29xxPxBCqwSYweE9Rd56vX9z572P2tNS1Dfqltu9A
